# Generated by Django 5.0.2 on 2024-02-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_filliere_student_modules_visitedcourses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedcourses',
            name='formatted_duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
