# Generated by Django 5.0.2 on 2024-02-22 15:57

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('users', '0003_profprofile_studentprofile_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_naissance',
        ),
        migrations.AddField(
            model_name='student',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='modules',
            field=models.ManyToManyField(related_name='students', to='course.module'),
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path_profile),
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path_profile)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('prof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
