# Generated by Django 5.0.2 on 2024-03-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_visitedcourses_formatted_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenquiz',
            name='score',
            field=models.IntegerField(),
        ),
    ]
