# Generated by Django 5.0.2 on 2024-02-25 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_visitedcourses_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenquiz',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
