# Generated by Django 5.0.2 on 2024-03-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-posted',)},
        ),
    ]
