# Generated by Django 5.0.2 on 2024-02-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
    ]
