# Generated by Django 5.0.2 on 2024-02-21 18:16


from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field= models.TextField(null=False),
        ),
    ]
