# Generated by Django 5.0.2 on 2024-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
