# Generated by Django 5.0.2 on 2024-02-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_filliere_notification_is_course_notif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_for_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
